job('first-maven-project-via-dsl') {
    description("First Maven Project Generated by DSL on ${new Date()}")
    scm {
        github('https://github.com/JavaShopee/MavenServlet.git', 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'MavenServlet/pom.xml')
    }
    publishers {
        archiveArtifacts '**/*.jar'
    }
}